name: build new project

on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Free Disk Space (Ubuntu)
      uses: insightsengineering/disk-space-reclaimer@v1
      with:
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true
        docker-images: true
        tools-cache: true

    - name: "Check disk space"
      run: df . -h

    - name: "Setup env"
      uses: JRMurr/direnv-nix-action@v4.1.0

    - name: "Check disk space"
      run: df . -h

    - name: generate new project
      run: ./setup.sh run_new_project
      shell: bash
